### ISSUE TITLE
Allow users to see the full list of available verbs 

### ISSUE THREAD

**Issue by redouane59** [badjilounes/dz-dialect-app#7]
Replace free text field by a drop down list or an autocomplete field with possible values only.
See [/get-elements endpoint](https://app.swaggerhub.com/apis/redouane59/dz-dialect-api/1.2.0#/default/get_get_elements).
![image](https://user-images.githubusercontent.com/4500524/168331637-6e45073a-5d6d-4234-9799-172ef6447d87.png)

**Comment by badjilounes** [comment]
https://github.com/badjilounes/dz-dialect-app/pull/12
